### ISSUE TITLE
This is the best AI

### ISSUE THREAD

**Issue by wubo0067** [Zulban/battleship-ai#3]
https://play.google.com/store/apps/details?id=com.taiqigame.sailcraft2，Much better than you

**Comment by Zulban** [comment]
Cool story bro. I especially like this review:

> Minor improvements, lots of new pointless features compared to SailCraft Online. And ever since its release, the old SC:P is virtually unplayable because of connectivity issues, while this one still only hangs on occasion.

You should learn the difference between "AI" and "pretty pictures".

By the way, making a very good battleship AI is extremely easy. That's why I use this project to teach AI to kids.

**Comment by Zulban** [comment]
You should try to better understand the different goals of these two projects.
